server:
  port: 8282
  servlet:
    context-path: /api

spring:
  application:
    name: e-clinique-backend

  # ==== PostgreSQL local ====
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eclinique}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: "eCliniqueSecretKeyForJwtSigningMustBeLongEnough1234567890"
    expiration-ms: 86400000  # 24h
  cors:
    allowed-origins: "http://localhost:4200"
  stock:
    seuil-alerte-defaut: 10

springdoc:
  swagger-ui:
    path: /swagger-ui.html


 #mvn -f /Users/mac/Desktop/e-clinique/backend/pom.xml spring-boot:run -Dspring-boot.run.profiles=h2